apiVersion: v1
kind: Service
metadata:
  name: mc01
  namespace: vprofile
spec:
  type: ClusterIP
  selector:
    app: memcached
  ports:
    - name: memcached
      port: 11211
      targetPort: 11211
