apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    app: tomcat
spec:
  type: ClusterIP
  selector:
    app: tomcat
  ports:
    - name: http
      port: 8080       # Service port
      targetPort: 8080  # Container port
      protocol: TCP
