---
- name: remove old node joined marker
  file:
    path: "{{ ansible_env.HOME }}/node_joined.txt"
    state: absent

- name: join cluster
  shell: "{{ hostvars['master']['join_command'] }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt
